logging:
  config: classpath:log4j2/log4j2.xml
spring:
  redis:
    host: 172.16.114.210
    port: 6378
    password: douzone1!
  elasticsearch:
    rest:
      uris: 172.16.124.176:9200

clinic:
  redis:
    host: 10.72.113.13
    port: 6379
    password: douzone1!
wehago:
  serviceCode: cliniccommon
  tms:
    url: http://172.16.125.25:8080/HISTMS/services/duzon
  redis:
    host: 172.16.114.210
    port: 6379
    password: douzone1!