#logging:
#  config: classpath:log4j.xml
server:
  servlet:
    context-path: /wehagoh
spring:
  mvc:
    servlet:
      path: /clinicsupport
  profiles:
    active: ${springProfilesActive}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      #dialect: org.hibernate.dialect.MariaDBDialect # Mariadb에 맞는 방언 설정
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  logMessage:
    test: \ud14c\uc2a4\ud2b8
clinic:
  pass:
    uri: /clinicsupport/alivecheck