logging:
  config: classpath:log4j2/log4j2.xml
spring:
  redis:
    host: 172.16.114.210
    port: 6379
    password: douzone1!
  elasticsearch:
    rest:
      uris: 172.16.124.176:9200
  kafka:
    consumer:
      bootstrap-servers: 172.16.125.38:9092
    producer:
      bootstrap-servers: 172.16.125.38:9092

clinic:
  redis:
    host: 172.16.124.139
    port: 6379
    password: douzone1!
wehago:
  serviceCode: cliniccommon
  tms:
    url: http://172.16.125.25:8080/HISTMS/services/duzon
  redis:
    host: 172.16.114.210
    port: 6379
    password: douzone1!